version: '3.4'

services:
  MCR.App:
    image: ${DOCKER_REGISTRY-}MCR.App
    build:
      context: .
      dockerfile: Dockerfile

  database:
    image: postgres:lastest
    container_name: Database
    environment:
      - POSTGRES_DB=projectsetup-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/database:/var/lib/postgresql/data
    ports:
      - 5432:5432    